config/routes.rb
require 'api_constraints'

Mygov::Application.routes.draw do
  mount_roboto

  devise_for :users, :path => '', :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations',
    :sessions => 'users/sessions',
    :unlocks => 'users/unlocks',
    :passwords => 'users/passwords'
  }
  devise_scope :user do
    get 'sign_up', :to => 'users/registrations#new', :as => :sign_up
    get 'thank_you', :to => 'users/registrations#thank_you', :as => :thank_you
    get 'sign_in', :to => 'users/sessions#new', :as => :sign_in
    get 'sign_out', :to => 'users/sessions#destroy', :as => :sign_out
    get 'active'  => 'users/sessions#active',  via: :get
    get 'timeout' => 'users/sessions#timeout', via: :get
  end
  get 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/allow' => 'oauth#allow'
  get 'oauth/unknown_app' => 'oauth#unknown_app', :as => :unknown_app
  resources :beta_signups, :only => [:create]
  #resource :user, :only => [:destroy]
  resource :user, only: [:edit, :destroy] do
    collection do
      get 'edit_password'
      put 'update_password'
      get 'edit_notification_settings'
      put 'update_notification_settings'
    end
  end
  resources :account, :only => [:index] do
    collection do
      resources :authentications
    end
  end
  resource :profile, :only => [:show, :edit, :update]
  resources :notifications, :only => [:index, :show, :create, :destroy]
  resources :tasks, :only => [:index, :show, :update, :destroy]
  resources :apps do
    member do
      get :uninstall
      get :leaving
    end
  end
  resources :task_items, :only => [:update, :destroy]
  get 'dashboard' => "home#dashboard"
  get 'developer' => "home#developer"
  get 'privacy-policy' => "home#privacy_policy", :as => :privacy_policy
  get 'terms-of-service' => "home#terms_of_service", :as => :terms_of_service
  get 'about' => "home#about", :as => :about
  get 'paperwork-reduction-act-statement' => "home#pra", :as => :pra
  get 'xrds' => "home#xrds", :as => :xrds

  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
      resource :profile, :only => [:show]
      resources :notifications, :only => [:create]
      resources :tasks, :only => [:index, :create, :show, :update]
      resources :forms, :only => [:create, :show]
      get "credentials/verify" => "credentials#verify", :as => :verify_credentials
    end
  end
  match "/404", :to => "errors#not_found"
  rack_error_handler = ActionDispatch::PublicExceptions.new('public/')
  match "/422" => rack_error_handler
  match "/500" => rack_error_handler
  match "/api/*path" => "application#xss_options_request", :via => :options

  root :to => 'home#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :data, :provider, :uid
  serialize :data, Hash
  validates_presence_of :provider, :uid
  validates_uniqueness_of :uid, :scope => [:provider]

  def self.auth_hash_from_uri(uri)
    openid_identity = CGI.parse(URI.parse(uri).query)["openid.identity"]
    uid = openid_identity.kind_of?(Array) ? openid_identity.first : openid_identity # openid.identity is an array
	  email = CGI.parse(URI.parse(uri).query)["openid.ext1.value.ext0"][0]
	  provider = CGI.parse(URI.parse(uri).query)["openid.return_to"].to_s.match(/(auth\/)(.+?)(\/)/)[2]
	  # If needed OmniAuth::AuthHash also extracts other information and attaches to :extra
	  OmniAuth::AuthHash.new(:uid => uid, :provider => provider, :info => {:email => email})
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :assign_user

  def index
    session[:after_auth_return_to] = authentications_path
    @authentications = @user.authentications
  end
  
  def new
    
  end
  
  def show
    @authentication = @user.authentications.find(params[:id])
  end
  
  def destroy
    @authentication = @user.authentications.find(params[:id])
    @authentication.destroy
    redirect_to authentications_path
  end
end

app/views/authentications/index.html.haml
.row
  .eight.columns
    %h2
      Authentication providers
    %p
      = flash_messages
    .panel
      %p
        = link_to 'Add an authentication provider to your account', new_authentication_path
      %table
        %tr
          %th
            Provider
          %th
            Actions
        - @authentications.each do |authentication|
          %tr
            %th
              = authentication.provider.titleize
            %th
              = link_to 'Delete', authentication_path(authentication), :method => :delete

    = link_to 'Back to Account Settings', account_index_path

app/views/authentications/new.html.haml
.row
	.eight.columns
		%h2
			Add a new authentication provider
		
.container
	.row
		.eight.columns
			.container
				.row
					.six.columns
						%p
							Do you already have an account with one of these sites?
					.six.columns
						.panel.side-panel
							%ul.button-list
								- Devise.omniauth_providers.each do |provider|
									- unless [:maxgov].include?(provider) or current_user.authentications.collect { |auth| auth.provider.to_sym }.include?(provider)
										%li
											= link_to provider.to_s.titleize, user_omniauth_authorize_path(:provider => provider, :error_return_to => authentications_url)