config/routes.rb
require 'api_constraints'

Mygov::Application.routes.draw do
  mount_roboto

  devise_for :users, :path => '', :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations',
    :sessions => 'users/sessions',
    :unlocks => 'users/unlocks',
    :passwords => 'users/passwords'
  }
  devise_scope :user do
    get 'sign_up', :to => 'users/registrations#new', :as => :sign_up
    get 'thank_you', :to => 'users/registrations#thank_you', :as => :thank_you
    get 'sign_in', :to => 'users/sessions#new', :as => :sign_in
    get 'sign_out', :to => 'users/sessions#destroy', :as => :sign_out
    get 'active'  => 'users/sessions#active',  via: :get
    get 'timeout' => 'users/sessions#timeout', via: :get
  end
  get 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/allow' => 'oauth#allow'
  get 'oauth/unknown_app' => 'oauth#unknown_app', :as => :unknown_app
  resources :beta_signups, :only => [:create]
  #resource :user, :only => [:destroy]
  resource :user, only: [:edit, :destroy] do
    collection do
      get 'edit_password'
      put 'update_password'
      get 'edit_notification_settings'
      put 'update_notification_settings'
    end
  end
  resources :account, :only => [:index] do
    collection do
      resources :authentications
    end
  end
  resource :profile, :only => [:show, :edit, :update]
  resources :notifications, :only => [:index, :show, :create, :destroy]
  resources :tasks, :only => [:index, :show, :update, :destroy]
  resources :apps do
    member do
      get :uninstall
      get :leaving
    end
  end
  resources :task_items, :only => [:update, :destroy]
  get 'dashboard' => "home#dashboard"
  get 'developer' => "home#developer"
  get 'privacy-policy' => "home#privacy_policy", :as => :privacy_policy
  get 'terms-of-service' => "home#terms_of_service", :as => :terms_of_service
  get 'about' => "home#about", :as => :about
  get 'paperwork-reduction-act-statement' => "home#pra", :as => :pra
  get 'xrds' => "home#xrds", :as => :xrds

  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
      resource :profile, :only => [:show]
      resources :notifications, :only => [:create]
      resources :tasks, :only => [:index, :create, :show, :update]
      resources :forms, :only => [:create, :show]
      get "credentials/verify" => "credentials#verify", :as => :verify_credentials
    end
  end
  match "/404", :to => "errors#not_found"
  rack_error_handler = ActionDispatch::PublicExceptions.new('public/')
  match "/422" => rack_error_handler
  match "/500" => rack_error_handler
  match "/api/*path" => "application#xss_options_request", :via => :options

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :developer, :privacy_policy, :terms_of_service, :about, :xrds]
  before_filter :assign_user, :except => [:index, :privacy_policy, :developer, :terms_of_service, :xrds]
  
  def index
    if current_user
      redirect_to :dashboard 
    else
      @beta_signup = BetaSignup.new
      render :layout => 'signup'
    end
  end
  
  def dashboard
    @today = Date.current
    @profile = @user.profile
    @notifications = @user.notifications.newest_first.limit(3)
    @uncompleted_tasks = @user.tasks.uncompleted.newest_first.limit(3)
  end
  
  def developer
  end

  def privacy_policy
  end
  
  def terms_of_service
  end
  
  def about
  end
  
  def pra
  end
    
  def xrds
    response.content_type = "application/xrds+xml"
  end
end

app/views/home/_administrative_settings.html.haml
.panel.tertiary.centered
  %ul.inline-list
    %li
      = link_to terms_of_service_path do
        %i{:class => "foundicon-page"}
        Terms of service
    %li
      = link_to privacy_policy_path do
        %i{:class => "foundicon-page"}
        Privacy policy
    %li
      = link_to pra_path do
        %i{:class => "foundicon-page"}
        Paperwork Reduction Act Statement

app/views/home/_administrative_sidebar.html.haml
.panel.tertiary
  %ul.panel-list
    %li
      = link_to terms_of_service_path do
        %i{:class => "foundicon-page"}
        Terms of service
    %li
      = link_to privacy_policy_path do
        %i{:class => "foundicon-page"}
        Privacy policy
    %li
      %p
        OMB No: 3090-00XX
      %p
        Expires: XX/XX/XXXX
      %p
        Paperwork Reduction Act Statement - This information collection meets the requirements of 44 U.S.C. § 3507, as amended by section 2 of the Paperwork Reduction Act of 1995. You do not need to answer these questions unless we display a valid Office of Management and Budget (OMB) control number. The OMB control number for this collection is 3090-00XX. We estimate that it will take 15 minutes to read the instructions, gather the facts, and answer the questions. Send only comments relating to our time estimate, including suggestions for reducing this burden, or any other aspects of this collection of information to: General Services Administration, Regulatory Secretariat (MVCB), ATTN: Regulatory Secretariat/IC 3090-00XX, 1800 F Street, NW, 2nd Floor, Washington, DC 20405.

app/views/home/_dashboard_apps.html.haml
.panel.group{"data-magellan-destination" => "apps"}
  %a{:name => "apps"}
  %h3
    %i{:class => "foundicon-website"}
    Apps
  %p
    Apps are services that use your MyUSA Account to make interacting with government easier.
  .row
    .eleven.columns
      %p
        Check out all available apps in the #{link_to 'App Gallery', apps_path}.
      %p
        Are you a developer? #{link_to 'Learn how to create your own MyUSA app', developer_path}.

app/views/home/_dashboard_nav.haml
.group
  %ul.dashboard-navigation{"data-magellan-expedition" => ""} 
    %li.first{"data-magellan-arrival" => "profile"}
      %a.smoothScroll.tasks{:href => "#profile"}
        .arrow
        %i{:class => "foundicon-people"}
        Profile
    %li{"data-magellan-arrival" => "notifications"}
      %a.smoothScroll.tasks{:href => "#notifications"}
        .arrow
        %i{:class => "foundicon-mail"}
        Notifications
    %li{"data-magellan-arrival" => "tasks"}
      %a.smoothScroll.tasks{:href => "#tasks"}
        .arrow
        %i{:class => "foundicon-checkmark"}
        Tasks
    %li.last{"data-magellan-arrival" => "apps"}
      %a.smoothScroll.apps{:href => "#apps"}
        .arrow
        %i{:class => "foundicon-website"}  
        Apps

app/views/home/_dashboard_notifications.html.haml
.panel.group{"data-magellan-destination" => "notifications"}
  %a{:name => "notifications"}
  %h3
    %i{:class => "foundicon-mail"}
    Notifications
  %p
    Important updates related to government.
  .row
    .eleven.columns
      - if @notifications.empty?
        %p
          You currently have no notifications.
      - else
        %table
          %tr
            %th{:scope => "col"}
              From
            %th{:scope => "col"}
              Subject
            %th{:scope => "col"}
              Date
          - @notifications.each do |notification|
            %tr
              - if notification.app
                %td
                  = highlight_notification_if_unread(notification, notification.app.name)
              - else
                %td
                  = highlight_notification_if_unread(notification, 'MyUSA')
              %td
                %i.general.foundicon-mail
                = link_to highlight_notification_if_unread(notification), notification_path(notification)
              %td
                = highlight_notification_if_unread(notification, pretty_time(notification.received_at))
  .row
    .eleven.columns
      = link_to 'View all notifications', notifications_path

app/views/home/_dashboard_tasks.html.haml
.panel.group{"data-magellan-destination" => "tasks"}
  %a{:name => "tasks"}
  %h3
    %i{:class => "foundicon-checkmark"}
    Tasks
  %p
    Guides for getting stuff done with government.
  .row
    .eleven.columns
      - if @uncompleted_tasks.empty?
        %p    
          You currently have no tasks.
      - else
        %table
          %tr
            %th{:scope => "col"}
              Name
            %th{:scope => "col"}
              App
          - @uncompleted_tasks.each do |task|
            %tr
              %td
                = link_to task.name, task_path(task)
              %td
                = task.app.name
  .row
    .eleven.columns
      = link_to 'View all tasks', tasks_path

app/views/home/_footer_links.haml
.panel.tertiary
  %ul.inline-list
    %li
      = link_to terms_of_service_path do
        %i{:class => "foundicon-page"}
        Terms of service
    %li
      = link_to privacy_policy_path do
        %i{:class => "foundicon-page"}
        Privacy policy
        
    %li
      <a href="/developer"><i class="foundicon-tools"></i> Developers</a>

app/views/home/about.html.haml
.row
  .eight.columns
    :markdown
    
      ## The Vision
      
      Project MyUSA is one of five initiatives that are part of the <a href="http://www.whitehouse.gov/innovationfellows">White House Presidential Innovation Fellows program</a>. This new program is bringing in top innovators from outside government to work with top innovators inside government to create real and substantial changes that will in a very short time frame benefit the American people, save taxpayers money, and help create new jobs.
      
      The purpose of Project MyUSA is to reimagine how citizens interact with government through an experience designed around their needs rather than a confusing and fragmented bureaucracy. 
      
      At its core, MyUSA is aimed at better serving the common needs of all Americans, but we are also creating a platform that makes it easy for our our partners in agencies across government to do that in their own way. On the citizen side there’s a lot of redundancy and duplication of effort when filling out forms or looking for answers to common questions. There’s also a lot of duplication of effort by agencies around these services, and a high barrier to entry to implement user management and persistency for personalized services. 
      
      In order to address these issues, MyUSA aims to establish a platform that provides trusted authentication and personalized services as well as a more simplified and unified experience for interactions with government in general. It will also include a toolkit for agencies to leverage the power of the platform, utilizing this new MyUSA login service’s personalization and unified experience. 
    

app/views/home/dashboard.html.haml
.row
  .one.columns.navigation
    = render :partial => 'dashboard_nav' 
  .eleven.columns.dashboard
    = flash_messages
    = render :partial => 'dashboard_profile'
    = render :partial => 'dashboard_notifications'
    = render :partial => 'dashboard_tasks'
    = render :partial => 'dashboard_apps' 
.row
  .twelve.columns    
    = render :partial => 'administrative_settings'

app/views/home/index.html.haml
.row
  .ten.columns.centered.banner
    %h2
      = t(:take_control)

.signup-form.margin-top
  .row
    .six.columns.centered
      %h3
        Try it out
      #signup-form
        #fieldset
          = form_for @beta_signup, html: {novalidate: true} do |form|
            = flash_messages
            = form.label :email
            = form.email_field :email, explanation_not_required: true
            = form.submit t(:sign_up), :class => 'large button positive '
  
      %p.disclaimer
        %a.plain{:href => "http://myusa.tumblr.com/about"}= t(:read_more)

app/views/home/pra.html.haml
.row
  .eight.columns.centered
    .panel

      %h3 Paperwork Reduction Act Notice
  
      %p OMB No: 3090-00XX
  
      %p Expires: XX/XX/XXXX
  
      %p
        Paperwork Reduction Act Statement - This information collection meets the requirements of 44 U.S.C. § 3507, as amended by section 2 of the Paperwork Reduction Act of 1995. You do not need to answer these questions unless we display a valid Office of Management and Budget (OMB) control number. The OMB control number for this collection is <inset number>. We estimate that it will take _____ minutes to read the instructions, gather the facts, and number answer the questions. Send only comments relating to our time estimate, including suggestions for reducing this burden, or any other aspects of this collection of information to: General Services Administration, Regulatory Secretariat (MVCB), ATTN: Regulatory Secretariat/IC 3090-00XX, 1275 First Street, NE., 7th Floor, Washington, DC 20417.

app/views/home/privacy_policy.html.haml
.row
  .eight.columns
    :markdown
    
      ## Privacy policy
    
      We hold your privacy in the highest regard. MyUSA collects some anonymous information automatically to help us improve the service (such as what parts of our system are being used when).  MyUSA also gives you an option to provide basic personal information, which we’ll use to customize your experience and simplify many common tasks. MyUSA has a few fundamental principles:
    
      1. Your personal information will only be used to improve or customize your experience.
      2. The information you provide is your information and you have the ultimate say in how it's used. 
      3. We'll always ask before we share your information with an agency or other government entity, and unless you say otherwise, it will remain private to you (except where required by law, as detailed in our [System of Records Notice](http://www.gpo.gov/fdsys/pkg/FR-2013-07-05/pdf/2013-16124.pdf)).
      4. We never store personal information on our servers unless required for the on-going operation of one of our services.
    
      ### Generally
    
      We are committed to protecting the privacy of our users. We collect no personal information unless you choose to provide that information to us.
    
      ### Information collected automatically
    
      Like most website operators, as you use our service, either directly or indirectly, we may collect and store the following non-personally-identifiable (a.k.a. anonymous) information about your visit:
    
      * the date and time you access MyUSA;
      * the various components of MyUSA you access;
      * if you access the MyUSA from another website or application - the identity of that third-party;
      * the technical capabilities of the computer you use to access our site, and
      * the IP address (an anonymous number automatically assigned to your computer whenever you are surfing the internet) from which you access MyUSA.
    
      We use this information, in the aggregate, to make MyUSA more useful to users — to learn about the number of and type of users of MyUSA, the components utilized, the types of technology used, to detect operational problems, and to improve MyUSA's overall security.
    
      ### Information that you provide voluntarily
    
      Certain users of our service choose to interact with it in ways that require us to gather personally-identifying information. The amount and type of information that we gather depends on the nature of the interaction. For example, if you add your name and street address to your MyUSA profile, we may offer to pre-fill common fields as you complete a form. In each case, we collect such information only insofar as is necessary or appropriate to fulfill the purpose of the user's interaction with us. We do not disclose personally-identifying information other than as described in our [System of Records Notice](http://www.gpo.gov/fdsys/pkg/FR-2013-07-05/pdf/2013-16124.pdf). Users may refuse to supply personally-identifying information at any time, with the understanding that it may prevent them from engaging in certain website-related activities.
    
      ### Login information
    
      When using our Service, you may be prompted with the opportunity to create a MyUSA account, or use an existing, third-party service to identify yourself (such as Google or PayPal). If you chose to do so, MyUSA will have access to the e-mail address you provide directly to MyUSA, or, possibly, indirectly via the third-party service. Unless you explicitly state otherwise, this pseudo-anonymous information will remain private to your account, and will only be used for notification and to simplify the process of retrieving your account on subsequent uses of the MyUSA Service.
    
      ### Profile information
    
      The Service offers the opportunity to store personally identifiable information (such as your name or address). We want you to feel comfortable trusting MyUSA with this basic profile information. Storing such information allows MyUSA to better customize many common tasks, such as pre-filling common fields across multiple forms. This information will remain private to your account, and will only be shared with government agencies if you explicitly grant permission on a case-by-case basis or where required by law.  You may delete your personal information at any time.
    
      ### Prohibition on use of personal information
    
      You take your privacy seriously, and so do we. At no time will your profile or login information (the information you provide voluntarily) be used without your explicit permission (except where required by law) or combined with the automatically collected, anonymous information, or otherwise used to identify or track your individual use of the Service.
    
      ### How information is used
    
      The information we collect is used to improve our service such as providing you with a more customized or simpler experience. We make every effort to disclose clearly how information is used at the point where it is collected so that you can determine for yourself whether you wish to provide the information.
    
      ### Sharing and disclosure
    
      The information you give us is kept private, and is not shared with anyone, other than with your explicit permission, or as required by law.  For more details on how we may share your information, please read our [System of Records Notice](http://www.gpo.gov/fdsys/pkg/FR-2013-07-05/pdf/2013-16124.pdf).
    
      ### Retention of information
    
      We destroy the information we collect when the purpose for which it was provided has been fulfilled, unless we are required to keep it longer by statute or official policy. Electronically submitted information is maintained and destroyed according to the principles of the Federal Records Act and the regulations and records schedules approved by the National Archives and Records Administration. In some cases information submitted to us may become an agency record and therefore might be subject to a Freedom of Information Act request.
    
      ### Security 
    
      For site security purposes and to ensure that this service remains available to all users, we employ software to monitor network traffic to identify unauthorized attempts to upload or change information, or otherwise cause damage.

      Except for authorized law enforcement investigations, no other attempts are made to identify individual users or their usage habits. Raw data logs are used for no other purposes and are scheduled for regular destruction in accordance with National Archives and Records Administration guidelines.

      If such monitoring reveals evidence of possible abuse or criminal activity, such evidence may be provided to appropriate law enforcement officials. Unauthorized attempts to upload or change information on this server are strictly prohibited and may be punishable under the Computer Fraud and Abuse Act of 1986 and the National Information Infrastructure Protection Act or other law.

      ### Linking policy

      MyUSA may link to websites created and maintained by other public and/or private organizations as outlined in [USA.gov’s Linking Policy](http://www.usa.gov/About/Linking-Policy.shtml). If you click a link to an outside website, you will leave the MyUSA site and are subject to the privacy and security policies of the owners/sponsors of the outside website.

      The General Services Administration (GSA) and MyUSA do not control or guarantee the accuracy, relevance, timeliness, or completeness of information contained on a linked website.

      GSA and MyUSA do not endorse the organizations sponsoring linked websites and we do not endorse the views they express or the products/services they offer.

      GSA and MyUSA cannot authorize the use of copyrighted materials contained in linked websites. Users must request such authorization from the sponsor of the linked website.

      GSA and MyUSA are not responsible for transmissions users receive from linked websites.

      GSA and MyUSA do not guarantee that outside websites comply with Section 508 (accessibility requirements) of the Rehabilitation Act.
    
      ### Cookies
    
      A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. In order to provide a more streamlined experience and to track aggregate usage information, by default, we store small amounts of data on your computer. We uses cookies to help identify and track visitors, their usage of our services, and their website access preferences.  We also use cookies to maintain your login session.  If you wish to opt-out of this feature, you may do so by following [these instructions](http://www.usa.gov/optout-instructions.shtml), although due to technical limitations, you may lose the ability to access certain information or services.

      ### Interaction with children
    
      This website and its associated services is not intended to be accessed by children under the age of 18.
    
      ### Your rights
    
      #### Privacy Act
    
      If any personal information you provide will be maintained in a Privacy Act system of records, you will be notified at the point of collection, as to whether providing information is mandatory or voluntary, and the effects of not providing all or any part of the requested information. Clicking a form "submit" button will constitute consent in this regard. Visit our [Privacy Act Web Page](http://www.gsa.gov/portal/content/104278) for additional information.
    
      #### Freedom of information
    
      Under the Freedom of Information Act (FOIA) and the Privacy Act of 1974, to the extent applicable, you have certain rights to obtain information about you that may be in our records. For more information about the circumstances under which you can get and correct this information, visit [our FOIA Web Page](http://www.gsa.gov/portal/content/105305).
    
      #### Third party websites
    
      To better engage the public in ongoing dialog, we use several third-party platforms including bit.ly, Facebook, Twitter, Disqus, GitHub, and UserVoice. When interacting with our presence on those websites, you may reveal certain personal information to us or to third parties. Except when used for the purpose of responding to a specific message or request, we will neither use nor share nor retain such data.  We also do not use personal information made available by the user to these third-party sites.
    
      #### Usage statistics
    
      This website employs Google Analytics (a service from Google, Inc.) to collect aggregate usage information. In utilizing this analytics service, we maintain our existing standards in regards to the sharing and disclosure of information, security and privacy safeguards for the data, and the data retention policy, each described above.
    
      **We reserve the right to modify this policy at any time.**

  .four.columns
    = render :partial => 'administrative_sidebar'      
      
      

app/views/home/xrds.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<xrds:XRDS xmlns:xrds="xri://$xrds" xmlns="xri://$xrd*($v*2.0)">
  <XRD>
    <Service priority="0">
      <Type>http://specs.openid.net/auth/2.0/return_to</Type>
    <% User.omniauth_providers.each do |provider| %>
      <URI><%= url_for(:action => provider, :controller => 'users/omniauth_callbacks', :protocol => 'https', :only_path => false) %></URI>
    <% end %>
    </Service>
  </XRD>
</xrds:XRDS>