config/routes.rb
require 'api_constraints'

Mygov::Application.routes.draw do
  mount_roboto

  devise_for :users, :path => '', :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations',
    :sessions => 'users/sessions',
    :unlocks => 'users/unlocks',
    :passwords => 'users/passwords'
  }
  devise_scope :user do
    get 'sign_up', :to => 'users/registrations#new', :as => :sign_up
    get 'thank_you', :to => 'users/registrations#thank_you', :as => :thank_you
    get 'sign_in', :to => 'users/sessions#new', :as => :sign_in
    get 'sign_out', :to => 'users/sessions#destroy', :as => :sign_out
    get 'active'  => 'users/sessions#active',  via: :get
    get 'timeout' => 'users/sessions#timeout', via: :get
  end
  get 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/allow' => 'oauth#allow'
  get 'oauth/unknown_app' => 'oauth#unknown_app', :as => :unknown_app
  resources :beta_signups, :only => [:create]
  #resource :user, :only => [:destroy]
  resource :user, only: [:edit, :destroy] do
    collection do
      get 'edit_password'
      put 'update_password'
      get 'edit_notification_settings'
      put 'update_notification_settings'
    end
  end
  resources :account, :only => [:index] do
    collection do
      resources :authentications
    end
  end
  resource :profile, :only => [:show, :edit, :update]
  resources :notifications, :only => [:index, :show, :create, :destroy]
  resources :tasks, :only => [:index, :show, :update, :destroy]
  resources :apps do
    member do
      get :uninstall
      get :leaving
    end
  end
  resources :task_items, :only => [:update, :destroy]
  get 'dashboard' => "home#dashboard"
  get 'developer' => "home#developer"
  get 'privacy-policy' => "home#privacy_policy", :as => :privacy_policy
  get 'terms-of-service' => "home#terms_of_service", :as => :terms_of_service
  get 'about' => "home#about", :as => :about
  get 'paperwork-reduction-act-statement' => "home#pra", :as => :pra
  get 'xrds' => "home#xrds", :as => :xrds

  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
      resource :profile, :only => [:show]
      resources :notifications, :only => [:create]
      resources :tasks, :only => [:index, :create, :show, :update]
      resources :forms, :only => [:create, :show]
      get "credentials/verify" => "credentials#verify", :as => :verify_credentials
    end
  end
  match "/404", :to => "errors#not_found"
  rack_error_handler = ActionDispatch::PublicExceptions.new('public/')
  match "/422" => rack_error_handler
  match "/500" => rack_error_handler
  match "/api/*path" => "application#xss_options_request", :via => :options

  root :to => 'home#index'
end

app/views/apps/_apps.html.haml
.row
  .four.columns 
    .panel.group
      .row
        .four.columns
          = image_tag app.logo.url(:thumb), alt: "#{app.name} logo"
      .row
        .six.columns
          %h3
            = link_to(app.name, app_path(app))
            = " (Authorized)" if @user_installed_apps.include?(app)
          %p
            = app.short_description

app/views/apps/_form.html.haml
:css
  .camo{
    display:none;
  }


%ul
  %li
    = f.label :name
    = f.text_field :name
  %li
    = f.label :description
    = f.text_area :description, :rows=>5
  %li
    = f.label(:short_description, 'Short Description')
    = f.text_field :short_description
  %li.upcase
    = f.label(:url, 'URL')
    = f.text_field :url
  %li
    = f.label(:redirect_uri, "Redirect URI")
    = f.text_field :redirect_uri
  %li
    = f.label :logo
    = f.file_field :logo
  %li
    = f.label :custom_text
    = f.text_field :custom_text
  %li
    = label_tag 'app_oauth_scopes' do
      %p
        Select which parts of the MyUSA API your application will use:
      %ul
        - @scope_groups.each do |oauth_scope|
          %li
            = render :partial => 'oauth_scope_checkbox', :locals => {:app => @app, :oauth_scope => oauth_scope, :index => oauth_scope.id, :is_parent => true}
            .camo{id: "camo_#{oauth_scope.scope_name.split(/\./)[0]}"}
              - if @grouped_scopes[oauth_scope.scope_name.to_sym]
                %ul
                  - @grouped_scopes[oauth_scope.scope_name.to_sym].each do |grouped_oauth_scope|
                    %li
                      = render :partial => 'oauth_scope_checkbox', :locals => {:app => @app, :@sub_scope => grouped_oauth_scope,:oauth_scope => grouped_oauth_scope, :index => oauth_scope.id, :is_parent => false}

app/views/apps/_oauth_scope_checkbox.html.haml
= label_tag "app[app_oauth_scopes_attributes][#{oauth_scope.id}][oauth_scope_id]" do
  - checkbox_options = is_parent ? {"parent_value" => oauth_scope.scope_name} : {"parent_scope" => oauth_scope.scope_name.split(/\./)[0]}
  = check_box_tag "app[app_oauth_scopes_attributes][#{oauth_scope.id}][oauth_scope_id]", oauth_scope.id, @app.app_oauth_scopes.collect(&:oauth_scope_id).include?(oauth_scope.id) ? true : false, checkbox_options    
  - if is_parent
    = oauth_scope.parent_readable_name
  - else
    = oauth_scope.readable_name

app/views/apps/edit.html.haml
.row
  .twelve.columns
    %h3
      Edit your MyUSA App
.row
  .eight.columns
    = form_for @app do |f|
      = render :partial => "form", :locals => {:f => f}
      = f.submit 'Update your MyUSA App', :class => 'button positive'
      = link_to 'Cancel', app_path(@app)
      &nbsp;&nbsp;
      - if @app.can_delete?
        = link_to app_path(@app), :method => :delete, :data => { :confirm => 'This cannot be undone.' }, :class => '' do
          %i{:class => 'foundicon-remove'}
          Remove 

app/views/apps/index.html.haml
.row{:style => 'padding-bottom: 10px;'}
  .six.columns
    %h3
      MyUSA Applications
  .six.columns{:style => 'text-align: right;'}
    = link_to 'Register a new MyUSA App', new_app_path, :class => 'button positive'
.row
  .twelve.columns
    - @apps.each do |app|
      = render :partial => 'apps', :locals => { :app => app }
-  unless @sandbox_apps.empty?
  .row
    .twelve.columns
      %h3
        Your Applications
  .row
    .twelve.columns
      - @sandbox_apps.each do |app|
        = render :partial => 'apps', :locals => { :app => app }
  

app/views/apps/leaving.html.haml
- content_for :head do
	= tag('meta', :'http-equiv' => "refresh", :content => "#{Rails.application.config.apps_leaving_delay};#{URI.escape @app.url}")  

.row
	.eight.columns
		- if @put_leaving_usa
			%h2
				#{t('leaving_myusa')}
		%p
			#{t('apps_leaving')} #{link_to @app.url, @app.url}.
		%p
			- if @put_leaving_usa
				#{t('not_part_of_myusa')}.

app/views/apps/new.html.haml
.row
  .twelve.columns
    %h3
      Create a new MyUSA App
.row
  .eight.columns
    = form_for @app do |f|
      - if @app.errors.any?
        .alert-box.alert
          = error_messages_for(@app)
      = render :partial => "form", :locals => {:f => f}
      = f.submit 'Register New MyUSA App', :class => 'button positive'
      = link_to 'Cancel', apps_path

app/views/apps/show.html.haml
- if @client_secret
  .row
    .twelve.columns
      .alert-box
        %h5{:style => 'text-shadow: 0 0 0;'}
          Your application has been created.
        %p{:style => 'text-shadow: 0 0 0;'}
          Please note the following information; you will need it to access the MyUSA Citizen API from your application.  The client secret will not be available after you close this page.
          %ul
            %li{:style => 'text-shadow: 0 0 0;'}
              OAuth Client ID: #{@app.client_id}
            %li{:style => 'text-shadow: 0 0 0;'}
              OAuth Client Secret: #{@client_secret}
          You can return to this page and follow the 'Edit app information' link to update your app.
.row
  .two.columns
    = image_tag @app.logo.url(:medium)
  .ten.columns
    %h3
      - unless @app.url.nil? || @app.url.length < 1
        = link_to @app.name, leaving_app_path(@app)
      - else
        = @app.name
    %h5
      = @app.short_description
    %p
      = @app.description
    - if @user_installed_apps.include?(@app)
      %p
        You have authorized this app. 
      - if @app.oauth_scopes.any?
        %p
          This app has permission to:
        %ul
          - @app.oauth_scopes.each do |oauth_scope|
            %li
              = oauth_scope.description
      %p
        You can revoke this app's permissions by clicking the button below.
      %p
        = link_to 'Revoke access', uninstall_app_path(@app)
    - if @app.user == @user
      .panel.group
        %p
          You are the owner of this application.
        %ul
          %li
            App status: #{app_status(@app)}
          %li
            App OAuth Client ID: #{@app.client_id}
          %li
            = link_to 'Edit app information', edit_app_path(@app)