config/routes.rb
require 'api_constraints'

Mygov::Application.routes.draw do
  mount_roboto

  devise_for :users, :path => '', :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations',
    :sessions => 'users/sessions',
    :unlocks => 'users/unlocks',
    :passwords => 'users/passwords'
  }
  devise_scope :user do
    get 'sign_up', :to => 'users/registrations#new', :as => :sign_up
    get 'thank_you', :to => 'users/registrations#thank_you', :as => :thank_you
    get 'sign_in', :to => 'users/sessions#new', :as => :sign_in
    get 'sign_out', :to => 'users/sessions#destroy', :as => :sign_out
    get 'active'  => 'users/sessions#active',  via: :get
    get 'timeout' => 'users/sessions#timeout', via: :get
  end
  get 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/authorize' => 'oauth#authorize'
  post 'oauth/allow' => 'oauth#allow'
  get 'oauth/unknown_app' => 'oauth#unknown_app', :as => :unknown_app
  resources :beta_signups, :only => [:create]
  #resource :user, :only => [:destroy]
  resource :user, only: [:edit, :destroy] do
    collection do
      get 'edit_password'
      put 'update_password'
      get 'edit_notification_settings'
      put 'update_notification_settings'
    end
  end
  resources :account, :only => [:index] do
    collection do
      resources :authentications
    end
  end
  resource :profile, :only => [:show, :edit, :update]
  resources :notifications, :only => [:index, :show, :create, :destroy]
  resources :tasks, :only => [:index, :show, :update, :destroy]
  resources :apps do
    member do
      get :uninstall
      get :leaving
    end
  end
  resources :task_items, :only => [:update, :destroy]
  get 'dashboard' => "home#dashboard"
  get 'developer' => "home#developer"
  get 'privacy-policy' => "home#privacy_policy", :as => :privacy_policy
  get 'terms-of-service' => "home#terms_of_service", :as => :terms_of_service
  get 'about' => "home#about", :as => :about
  get 'paperwork-reduction-act-statement' => "home#pra", :as => :pra
  get 'xrds' => "home#xrds", :as => :xrds

  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
      resource :profile, :only => [:show]
      resources :notifications, :only => [:create]
      resources :tasks, :only => [:index, :create, :show, :update]
      resources :forms, :only => [:create, :show]
      get "credentials/verify" => "credentials#verify", :as => :verify_credentials
    end
  end
  match "/404", :to => "errors#not_found"
  rack_error_handler = ActionDispatch::PublicExceptions.new('public/')
  match "/422" => rack_error_handler
  match "/500" => rack_error_handler
  match "/api/*path" => "application#xss_options_request", :via => :options

  root :to => 'home#index'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head(prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#")
    = yield :head
    - if current_user && request.get? # If it's a post, then no redirect
      %noscript
        = refresh_meta_tag_conent
    = head_metadata(content_for?(:title) ? yield(:title) : "MyUSA", content_for?(:meta_description) ? yield(:meta_description) : t(:meta_description))
    = csrf_meta_tags
    = stylesheet_link_tag "fonts", :media => "all"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "general_foundicons", :media => "all"
    /[if !IE 7]
      = stylesheet_link_tag "ie7", :media => "all"
    /[if lt IE 9]
      = stylesheet_link_tag "general_foundicons_ie7", :media => "all"
    = favicon_link_tag '/favicon.ico', :rel => 'shortcut icon'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :sizes => '72x72', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :sizes => '114x114', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :sizes => '144x144', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = javascript_include_tag 'modernizr'

  %body
    #wrap
      #header
        .nav-container.group
          .row
            .six.columns
              %a{ :href => root_url }
                %h1
                  - if current_user and current_user.profile.first_name.present?
                    %span.personal-name
                      #{current_user.profile.first_name}'s
                  My<span>USA</span>
            .six.columns.align-right
              - if !current_user && request.path != sign_in_path
                %h3.tagline
                  =t(:sign_in_prompt)
                  =link_to t(:sign_in_link), sign_in_path
              - if current_user
                %h3.tagline
                  = link_to 'MyUSA Dashboard', root_url
                  |
                  = link_to 'Account Settings', account_index_path
                  |
                  = link_to t(:sign_out), sign_out_path
      #main
        %a{:name => "top"}
        .nav-container.group
          .row
            .twelve.columns
        .container.group
          %noscript
            = session_about_to_timeout_message_no_script
          = session_about_to_timeout_message
          = yield
        - unless current_user
          .no-toolbar

      /
        Javascripts
        \==================================================
      / Placed at the end of the document so the pages load faster
      = javascript_include_tag "application"
      :javascript

          if ($('#meta-refresh').length > 0) {
            var mr = document.getElementById("meta-refresh");
            console.log(mr);
            mr.parentNode.removeChild(mr);
          }
      = content_for :scripts
      = analytics_init if Rails.env.production?
      - if current_user
        = auto_session_timeout_js timeout:  User.timeout_in, frequency: Rails.application.config.session_check_frequency, start: 1, warning: Rails.application.config.session_timeout_warning_seconds

app/views/layouts/notification_mailer.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Facebook sharing information tags
    %meta{:content => "MyUSA", :property => "og:title"}/
    %title *MyUSA*
    :css
      /* Client-specific Styles */
      #outlook a{padding:0;} /* Force Outlook to provide a "view in browser" button. */
      body{width:100% !important;} .ReadMsgBody{width:100%;} .ExternalClass{width:100%;} /* Force Hotmail to display emails at full width */
      body{-webkit-text-size-adjust:none;} /* Prevent Webkit platforms from changing default text sizes. */

      /* Reset Styles */
      body{margin:0; padding:0;}
      img{border:0; height:auto; line-height:100%; outline:none; text-decoration:none;}
      table td{border-collapse:collapse;}
      #backgroundTable{height:100% !important; margin:0; padding:0; width:100% !important;}

      /* Template Styles */

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: COMMON PAGE ELEMENTS /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Page
      * @section background color
      * @tip Set the background color for your email. You may want to choose one that matches your company's branding.
      * @theme page
      */
      body, #backgroundTable{
      	/*@editable*/ background-color:#0F1F37;
      }

      /**
      * @tab Page
      * @section email border
      * @tip Set the border for your email.
      */
      #templateContainer{
      	/*@editable*/ border: 1px solid #DDDDDD;
      }

      /**
      * @tab Page
      * @section heading 1
      * @tip Set the styling for all first-level headings in your emails. These should be the largest of your headings.
      * @style heading 1
      */
      h1, .h1{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family: 'Helvetica Neue', Helvetica, Arial;
      	/*@editable*/ font-size:34px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Page
      * @section heading 2
      * @tip Set the styling for all second-level headings in your emails.
      * @style heading 2
      */
      h2, .h2{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:30px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Page
      * @section heading 3
      * @tip Set the styling for all third-level headings in your emails.
      * @style heading 3
      */
      h3, .h3{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:26px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Page
      * @section heading 4
      * @tip Set the styling for all fourth-level headings in your emails. These should be the smallest of your headings.
      * @style heading 4
      */
      h4, .h4{
      	/*@editable*/ color:#202020;
      	display:block;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:22px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	margin-top:0;
      	margin-right:0;
      	margin-bottom:10px;
      	margin-left:0;
      	/*@editable*/ text-align:left;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: PREHEADER /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Header
      * @section preheader style
      * @tip Set the background color for your email's preheader area.
      * @theme page
      */
      #templatePreheader{
      	/*@editable*/ background-color:#FAFAFA;
      }

      /**
      * @tab Header
      * @section preheader text
      * @tip Set the styling for your email's preheader text. Choose a size and color that is easy to read.
      */
      .preheaderContent div{
      	/*@editable*/ color:#505050;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:10px;
      	/*@editable*/ line-height:100%;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Header
      * @section preheader link
      * @tip Set the styling for your email's preheader links. Choose a color that helps them stand out from your text.
      */
      .preheaderContent div a:link, .preheaderContent div a:visited, /* Yahoo! Mail Override */ .preheaderContent div a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: HEADER /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Header
      * @section header style
      * @tip Set the background color and border for your email's header area.
      * @theme header
      */
      #templateHeader{
      	/*@editable*/ background-color:#FFFFFF;
      	/*@editable*/ border-bottom:0;
      }

      /**
      * @tab Header
      * @section header text
      * @tip Set the styling for your email's header text. Choose a size and color that is easy to read.
      */
      .headerContent{
      	/*@editable*/ color:#202020;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:34px;
      	/*@editable*/ font-weight:bold;
      	/*@editable*/ line-height:100%;
      	/*@editable*/ padding:0;
      	/*@editable*/ text-align:center;
      	/*@editable*/ vertical-align:middle;
      }

      /**
      * @tab Header
      * @section header link
      * @tip Set the styling for your email's header links. Choose a color that helps them stand out from your text.
      */
      .headerContent a:link, .headerContent a:visited, /* Yahoo! Mail Override */ .headerContent a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      #headerImage{
      	height:auto;
      	max-width:600px !important;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: MAIN BODY /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Body
      * @section body style
      * @tip Set the background color for your email's body area.
      */
      #templateContainer, .bodyContent{
      	/*@editable*/ background-color:#FFFFFF;
      }

      /**
      * @tab Body
      * @section body text
      * @tip Set the styling for your email's main content text. Choose a size and color that is easy to read.
      * @theme main
      */
      .bodyContent div{
      	/*@editable*/ color:#505050;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:14px;
      	/*@editable*/ line-height:150%;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Body
      * @section body link
      * @tip Set the styling for your email's main content links. Choose a color that helps them stand out from your text.
      */
      .bodyContent div a:link, .bodyContent div a:visited, /* Yahoo! Mail Override */ .bodyContent div a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      .bodyContent img{
      	display:inline;
      	height:auto;
      }

      /* /\/\/\/\/\/\/\/\/\/\ STANDARD STYLING: FOOTER /\/\/\/\/\/\/\/\/\/\ */

      /**
      * @tab Footer
      * @section footer style
      * @tip Set the background color and top border for your email's footer area.
      * @theme footer
      */
      #templateFooter{
      	/*@editable*/ background-color:#FFFFFF;
      	/*@editable*/ border-top:0;
      }

      /**
      * @tab Footer
      * @section footer text
      * @tip Set the styling for your email's footer text. Choose a size and color that is easy to read.
      * @theme footer
      */
      .footerContent div{
      	/*@editable*/ color:#707070;
      	/*@editable*/ font-family:Arial;
      	/*@editable*/ font-size:12px;
      	/*@editable*/ line-height:125%;
      	/*@editable*/ text-align:left;
      }

      /**
      * @tab Footer
      * @section footer link
      * @tip Set the styling for your email's footer links. Choose a color that helps them stand out from your text.
      */
      .footerContent div a:link, .footerContent div a:visited, /* Yahoo! Mail Override */ .footerContent div a .yshortcuts /* Yahoo! Mail Override */{
      	/*@editable*/ color:#336699;
      	/*@editable*/ font-weight:normal;
      	/*@editable*/ text-decoration:underline;
      }

      .footerContent img{
      	display:inline;
      }

      /**
      * @tab Footer
      * @section social bar style
      * @tip Set the background color and border for your email's footer social bar.
      * @theme footer
      */
      #social{
      	/*@editable*/ background-color:#FAFAFA;
      	/*@editable*/ border:0;
      }

      /**
      * @tab Footer
      * @section social bar style
      * @tip Set the background color and border for your email's footer social bar.
      */
      #social div{
      	/*@editable*/ text-align:center;
      }

      /**
      * @tab Footer
      * @section utility bar style
      * @tip Set the background color and border for your email's footer utility bar.
      * @theme footer
      */
      #utility{
      	/*@editable*/ background-color:#FFFFFF;
      	/*@editable*/ border:0;
      }

      /**
      * @tab Footer
      * @section utility bar style
      * @tip Set the background color and border for your email's footer utility bar.
      */
      #utility div{
      	/*@editable*/ text-align:center;
      }

		
  %body{:leftmargin => "0", :marginheight => "0", :marginwidth => "0", :offset => "0", :topmargin => "0"}
    %center
      %table#backgroundTable{:border => "0", :cellpadding => "0", :cellspacing => "0", :height => "100%", :width => "100%"}
        %tr
          %td{:align => "center", :valign => "top"}
            / // Begin Template Preheader \\
            %table#templateContainer{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
              %tr
                %td{:align => "center", :valign => "top"}
                  / // Begin Template Header \\
                  %table#templateHeader{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                    %tr
                      %td.headerContent
                        / // Begin Module: Standard Header Image \\
                        %img{:id => "headerImage campaign-icon", "mc:allowdesigner" => "", "mc:allowtext" => "", "mc:edit" => "header_image", "mc:label" => "header_image", :src => "https://my.usa.gov/assets/email-logo.png", :style => "max-width:600px;"}/
                        / // End Module: Standard Header Image \\
                  / // End Template Header \\
              %tr
                %td{:align => "center", :valign => "top"}
                  / // Begin Template Body \\
                  %table#templateBody{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "600"}
                    %tr
                      %td.bodyContent{:valign => "top"}
                        / // Begin Module: Standard Content \\
                        %table{:border => "0", :cellpadding => "20", :cellspacing => "0", :width => "100%"}
                          %tr
                            %td{:valign => "top"}
                              %div{"mc:edit" => "std_content00"}
                                = yield
                        / // End Module: Standard Content \\
                  / // End Template Body \\
              %tr
                %td{:align => "center", :valign => "top"}

app/views/layouts/signup.html.haml
!!! 5
%html.splash-page(lang="en")
  %head(prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#")

    = head_metadata(content_for?(:title) ? yield(:title) : "MyUSA", content_for?(:meta_description) ? yield(:meta_description) : "A platform for connecting people and government")
    
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag '/favicon.ico', :rel => 'shortcut icon'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :sizes => '72x72', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :sizes => '114x114', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :sizes => '144x144', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    = javascript_include_tag 'modernizr' 

  %body.sign-up   
    %div#wrap
      %div#main
        .nav-container.group
          .logo
            .row
              .ten.columns.centered
                %p.sign-in-bar.right
                  =t(:sign_in_prompt)
                  =link_to t(:sign_in_link), sign_in_path
                  
            .six.columns.centered
              %h1
                MyUSA
          = yield
            
          .secondary
            .row 
              .ten.columns.centered
                %ul.centered
                  %li
                    = link_to t(:about_myusa), "http://myusa.tumblr.com/about", :class => 'info'
                  %li
                    = link_to t(:developers), developer_path, :class => 'info'
                  %li
                    = link_to t(:digital_government), "http://www.whitehouse.gov/sites/default/files/omb/egov/digital-government/digital-government.html", :class => 'info'
                  %li
                    = link_to t(:privacy_policy), privacy_policy_path, :class => 'info'
                  %li
                    = link_to t(:terms_of_service), terms_of_service_path, :class => 'info'
      /
        Javascripts
        \==================================================
      / Placed at the end of the document so the pages load faster
      = javascript_include_tag "application"
      = content_for :scripts
      = analytics_init if Rails.env.production?